name: Build

on:
  workflow_call:
    outputs:
      publish:
        description: "Indicates if the project should be published to NPM"
        value: ${{ jobs.prepublish.outputs.publish }}

jobs:
  build:
    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [server, staff, web, ui]
    concurrency:
      group: ${{ github.workflow }} - ${{ matrix.package }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
      cancel-in-progress: true
    outputs:
      publish: ${{ steps.do-publish.outputs.publish }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Calculating Hash
        run: |
          echo "TURBO_VERSION=$( npm show turbo version )" >> $GITHUB_ENV
          echo "NPM_GLOBAL_MODULES=$( npm root -g )" >> $GITHUB_ENV
          echo "TURBO_HASH=$( npx --yes turbo run build --dry --only --filter=@kenthackenough/${{ matrix.package }} | grep = | grep Hash | tail -1 | cut -f2- -d= | xargs )" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Cache - Turbo
        id: turbo-cache
        with:
          path: |
            .turbo
            ${{ github.workspace }}/projects/*/.next/cache
          key: cache-turbo-build-${{ matrix.package }}-${{ hashFiles('package-lock.json') }}-${{ env.TURBO_HASH }}
          restore-keys: |
            cache-turbo-build-${{ matrix.package }}-${{ hashFiles('package-lock.json') }}-
      - name: Validate Hash
        run: |
          echo "FULL_TURBO=$( $(find .turbo -iname "${{ env.TURBO_HASH }}-*" | grep ${{ env.TURBO_HASH }}) && echo 'yes' || echo 'no' )" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Cache - NPM
        id: npm-cache
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/package.json
            ${{ github.workspace }}/github/scripts/*/node_modules
            ${{ github.workspace }}/*/*/node_modules
            ${{ github.workspace }}/*/*/dist
          key: cache-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cache-npm-
      - name: Installing Dependencies
        if: ${{ env.FULL_TURBO == 'no' }}
        run: npm install --no-audit --no-fund && git restore package-lock.json
      - name: Building
        run: npm run build -- --cache-dir=.turbo --filter=@kenthackenough/${{ matrix.package }}...
  

  prepublish:
    name: Check Version
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }} - ${{ matrix.package }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
      cancel-in-progress: true
    outputs:
      publish: ${{ steps.do-publish.outputs.publish }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Get Version
        id: get-version
        run: echo "PACKAGE_VERSION=$(node .github/scripts/github/get-version)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: prepublished
        with:
          key: cache-prepublish-${{ steps.get-version.outputs.PACKAGE_VERSION }}
          path: |
            .prepublish-cache
      - name: Check Publish
        id: do-publish
        run: echo "publish=${{steps.prepublished.outputs.cache-hit != 'true'}}" >> $GITHUB_OUTPUT
      - name: Copy Package.json to cache
        if: steps.prepublished.outputs.cache-hit != 'true'
        run: |
          mkdir -p .prepublish-cache
          cp package.json .prepublish-cache/package.json