name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [server, staff, web]
    concurrency:
      group: ${{ github.workflow }} - ${{ matrix.package }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - uses: actions/cache@v3
        id: turbo-cache
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
      - name: Installing Dependencies
        run: npm install
      - name: Linting - ${{ matrix.package }}
        run: npm run build --cache-dir=.turbo --filter=@kenthackenough/${{ matrix.package }}