name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [server, staff, web]
    concurrency:
      group: ${{ github.workflow }} - ${{ matrix.package }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Calculating Hash
        run: |
          echo "TURBO_VERSION=$( npm show turbo version )" >> $GITHUB_ENV
          echo "NPM_GLOBAL_MODULES=$( npm root -g )" >> $GITHUB_ENV
          echo "TURBO_HASH=$( npx --yes turbo run build --dry --only --filter=@kenthackenough/${{ matrix.package }} | grep = | grep Hash | tail -1 | cut -f2- -d= | cut -c 2- )" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Cache - Turbo
        id: turbo-cache
        with:
          path: |
            .turbo
          key: cache-turbo-build-${{ matrix.package }}-${{ hashFiles('package-lock.json') }}-${{ env.TURBO_HASH }}
          restore-keys: |
            cache-turbo-build-${{ matrix.package }}-${{ hashFiles('package-lock.json') }}-
      - name: Validate Hash
        run: |
          echo "FULL_TURBO=$( find .turbo -iname "${{ env.TURBO_HASH }}-*" | grep ${{ env.TURBO_HASH }} && "yes" || "no" )" >> $GITHUB_ENV
          echo "NPM_GLOBAL_MODULES=$( npm root -g )" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Cache - NPM
        id: npm-cache
        with:
          path: |
            ${{ github.workspace }}/projects/*/.next/cache
            ~/.npm
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/package.json
            ${{ github.workspace }}/github/scripts/*/node_modules
            ${{ github.workspace }}/*/*/node_modules
          key: cache-check-build-${{ matrix.package }}-${{ github.ref_name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cache-check-build-${{ matrix.package }}-${{ github.ref_name }}-
      - name: Installing Dependencies
        if: ${{ env.FULL_TURBO == 'no' }}
        run: npm install --no-audit --no-fund
      - name: Building
        run: npm run build -- --cache-dir=.turbo --only --filter=@kenthackenough/${{ matrix.package }}