name: Deploy

on:
  workflow_call:
    inputs:
      host:
        required: false
        type: string
        description: 'Server to SSH into'
      user:
        required: false
        type: string
        default: 'root'
        description: 'User to SSH into the host with'
      port:
        required: false
        type: string
        default: '22'
        description: 'Port that SSH is running on'
      key:
        required: false
        type: string
        description: 'SSH Key to authenticate with'
      directory:
        required: true
        type: string
        description: 'Directory to execute commands within'
    secrets:
      host:
        required: false
      key:
        required: false
      user:
        required: false
      port:
        required: false
  # workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:

  install:
    name: Install
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deployment' && (true || github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || contains(github.event.head_commit.message, '@deploy'))
    # Run commands to git fetch & install dependencies on the server
    steps:
      - name: Debug
        run: echo "Run commands to git fetch & install dependencies on the server"
      - name: Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.host || inputs.host }}
          port: ${{ secrets.port || inputs.port }}
          username: ${{ secrets.user || inputs.user }}
          key: ${{ secrets.key || inputs.key }}
          script_stop: true
          script: |
            cd ${{ inputs.directory }}
            whoami
      - name: Execute Commands 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.host }}
          port: ${{ inputs.port }}
          username: ${{ inputs.user }}
          key: ${{ secrets.key }}
          script_stop: true
          script: |
            cd ${{ inputs.directory }}
            ls


  build:
    name: Build
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [server, staff, web]
    # Run .github/scripts/server/deploy/${{ matrix.project }}.sh script on server
    steps:
      - name: Debug
        run: echo "Run .github/scripts/server/deploy/${{ matrix.project }}.sh script on server"
