name: Deploy

on:
  workflow_call:
    inputs:
      host:
        required: true
        description: 'Server to SSH into'
      user:
        required: false
        type: string
        default: 'root'
        description: 'User to SSH into the host with'
      port:
        required: false
        type: number
        default: 22
        description: 'Port that SSH is running on'
      directory:
        required: true
        description: 'Directory to execute commands within'
    secrets:
      KEY:
        required: true
        description: 'SSH Key to authenticate with'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  install:
    name: Install
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deployment' && (true || github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || contains(github.event.head_commit.message, '@deploy'))
    # Run commands to git fetch & install dependencies on the server
    steps:
      - name: Debug
        run: echo "Run commands to git fetch & install dependencies on the server"
      - name: Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.host }}
          port: ${{ inputs.port }}
          username: ${{ inputs.user }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ inputs.directory }}
            whoami
            pwd
            ls
            exit


  build:
    name: Build
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [server, staff, web]
    # Run .github/scripts/server/deploy/${{ matrix.project }}.sh script on server
    steps:
      - name: Debug
        run: echo "Run .github/scripts/server/deploy/${{ matrix.project }}.sh script on server"
