name: Deploy

on:
  workflow_call:
    secrets:
      HOST:
        required: true
        description: 'Server to SSH into'
      USER:
        required: true
        description: 'User to SSH into the host with'
      PORT:
        required: true
        description: 'Port that SSH is running on'
      KEY:
        required: true
        description: 'SSH Key to authenticate with'
      DIR:
        required: true
        description: 'Directory to execute commands within'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  install:
    name: Install
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deployment' && (true || github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || contains(github.event.head_commit.message, '@deploy'))
    # Run commands to git fetch & install dependencies on the server
    steps:
      - name: Debug
        run: echo "Run commands to git fetch & install dependencies on the server"
      - name: Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.HOST }}
          port: ${{ inputs.PORT }}
          username: ${{ inputs.USER }}
          key: ${{ inputs.KEY }}
          script: |
            cd ${{ inputs.DIR }}
            whoami
            pwd
            ls
            exit


  build:
    name: Build
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [server, staff, web]
    # Run .github/scripts/server/deploy/${{ matrix.project }}.sh script on server
    steps:
      - name: Debug
        run: echo "Run .github/scripts/server/deploy/${{ matrix.project }}.sh script on server"
