name: Deploy

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  install:
    name: Install
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deployment' && (github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || contains(github.event.head_commit.message, '@deploy'))
    # Run commands to git fetch & install dependencies on the server
    steps:
      - name: Debug
        run: echo "Run commands to git fetch & install dependencies on the server"

  build:
    name: Build
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [server, staff, web]
    # Run .github/scripts/server/deploy/${{ matrix.project }}.sh script on server
    steps:
      - name: Debug
        run: echo "Run .github/scripts/server/deploy/${{ matrix.project }}.sh script on server"

  status:
    name: Healthcheck
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [server, staff, web]
    # do `pm2 show ${{ matrix.project }}`
    steps:
      - name: Debug
        run: echo "do `pm2 show ${{ matrix.project }}`"
