name: Deploy

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Prepare:
    name: Prepare
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || contains(github.event.head_commit.message, '@deploy'))