name: Health

on:
  schedule:
    # This runs 4 times a day: https://crontab.guru/#0_0,4,7,8,12_*_*_*
    - cron: '0 0,4,7,8,12 * * *'
  workflow_call:
    inputs:
      host:
        required: false
        type: string
        description: 'Server to SSH into'
      user:
        required: false
        type: string
        description: 'User to SSH into the host with'
      port:
        required: false
        type: string
        description: 'Port that SSH is running on'
      key:
        required: false
        type: string
        description: 'SSH Key to authenticate with'
    secrets:
      host:
        required: false
      key:
        required: false
      user:
        required: false
      port:
        required: false
  workflow_dispatch:

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [api, staff, web]
    steps:
      - name: PM2 Status
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.host || inputs.host || secrets.DEPLOY_HOST_DEV }}
          port: ${{ secrets.port || inputs.port || secrets.DEPLOY_PORT_DEV }}
          username: ${{ secrets.user || inputs.user || secrets.DEPLOY_USER_DEV }}
          privateKey: ${{ secrets.key || inputs.key || secrets.DEPLOY_KEY_DEV }}
          command: |
            export TERM=xterm-256color
            export FORCE_COLOR=1
            pm2 status
            pm2 show khe-${{ matrix.project }}
            exit $(pm2 show khe-${{ matrix.project  }} | grep -c stopped);

