name: Lint

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    concurrency:
      group: lint
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Installing Dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Linting - Server
        run: yarn lint --filter=@kenthackenough/server
      - name: Linting - Staff
        run: yarn lint --filter=@kenthackenough/staff
      - name: Linting - Web
        run: yarn lint --filter=@kenthackenough/web