name: Check Publish

on:
  workflow_call:
    outputs:
      publish:
        description: "Indicates if the project should be published to NPM"
        value: ${{ jobs.build.outputs.publish }}

jobs:
  build:
    name: Check Publish
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }} - ${{ matrix.package }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
      cancel-in-progress: true
    outputs:
      publish: ${{ steps.do-publish.outputs.publish }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Get Version
        id: get-version
        run: echo "PACKAGE_VERSION=$(node .github/scripts/github/get-version)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: prepublished
        with:
          key: cache-prepublish-${{ steps.get-version.outputs.PACKAGE_VERSION }}
          path: |
            .prepublish-cache
      - name: Check Publish
        id: do-publish
        run: echo "publish=${{steps.prepublished.outputs.cache-hit != 'true'}}" >> $GITHUB_OUTPUT
      - name: Copy Package.json to cache
        if: steps.prepublished.outputs.cache-hit != 'true'
        run: |
          mkdir -p .prepublish-cache
          cp package.json .prepublish-cache/package.json