
name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    concurrency:
      group: publish
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: Installing Dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Building
        run: yarn build
      - name: Publish - Staff
        run: yarn publish
      - name: Linting - Web
        run: yarn lint --filter=@kenthackenough/web