
name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    concurrency:
      group: publish
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-workflow-cache
          path: |
            .workflow-cache
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@kenthackenough'
          cache: 'yarn'
      - name: Installing Dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Checking if we need to publish
        id: check-publish
        run: echo "DO_PUBLISH=$(node .github/scripts/github/do-publish)" >> $GITHUB_OUTPUT
      - name: Building
        if: ${{ steps.check-publish.outputs.DO_PUBLISH == 'yes' }}
        run: yarn build
      - name: Publish - Server
        if: ${{ steps.check-publish.outputs.DO_PUBLISH == 'yes' }}
        working-directory: projects/server
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish - Staff
        if: ${{ steps.check-publish.outputs.DO_PUBLISH == 'yes' }}
        working-directory: projects/staff
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish - Web
        if: ${{ steps.check-publish.outputs.DO_PUBLISH == 'yes' }}
        working-directory: projects/web
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: ${{ steps.check-publish.outputs.DO_PUBLISH == 'yes' }}
        run: |
          cp package.json .workflow-cache/package.json
          node .github/scripts/github/do-publish