
name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    concurrency:
      group: publish
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-workflow-cache
          path: |
            .workflow-cache
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@kenthackenough'
          cache: 'yarn'
      - name: Installing Dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Checking if we need to publish
        id: check-publish
        run: echo "DO_PUBLISH=$(node .github/scripts/github/do-publish)" >> $GITHUB_OUTPUT
      - name: Get Status
        run: echo "status = ${{ steps.check-publish.outputs.DO_PUBLISH }}"
      - name: if yes
        if: ${{ steps.check-publish.outputs.DO_PUBLISH == 'yes' }}
        run: echo "yes!"
      - name: if no
        if: ${{ steps.check-publish.outputs.DO_PUBLISH == 'no' }}
        run: echo "no!"

      # - run: cp package.json .workflow-cache/package.json
      # - name: Building
      #   run: yarn build
      # - name: Publish - Server
      #   working-directory: projects/server
      #   run: yarn publish --non-interactive
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Publish - Staff
      #   working-directory: projects/staff
      #   run: yarn publish --non-interactive
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Publish - Web
      #   working-directory: projects/web
      #   run: yarn publish --non-interactive
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}